remote_theme: pmarsceill/just-the-docs

title: Micro:bit

google_analytics: UA-131578130-1

aux_links:
    "Voir la source sur GitHub":
      - "//github.com/serresebastien/Micro-Bit"
      
exclude: ["LICENSE.txt", "README.md"]
